os: linux

language: node_js

node_js:
  - "12"
  - "10"

cache: npm

jobs:
  include:
    - stage: npm release

      script: skip

      # before_deploy:
      #   - echo "//registry.npmjs.org/:_authToken=${NPM_API_TOKEN}" > ~/.npmrc

      deploy:
        on:
          # tags: true
          all_branches: true
        provider: script
        script: npm whoami
        # script: npm publish --otp $(npx otp-cli totp generate -k "$NPM_OTP_SECRET")
        skip_cleanup: true
